version: '3.4'

services:
  build:
    image: ticket-checker-android-app-build:1.0
    container_name: ticket-checker-android-app-build
    build:
      context: .
      target: build
      args:
        SDK_URL: "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
        ANDROID_HOME: "/usr/local/android-sdk"
        ANDROID_VERSION: 29
        ANDROID_BUILD_TOOLS_VERSION: 29.0.3